In [7]:
# while loop
x=0
while x <= 10:
    print(x)
    x=x+1

0
1
2
3
4
5
6
7
8
9
10


In [9]:
# Making function 
def rewrite():
    print("sahan")
    print("Thilakshana")
    print("Dankelewathhtha")


In [11]:
rewrite()

sahan
Thilakshana
Dankelewathhtha


In [15]:
x= 0
while x<10:
    rewrite()
    x=x+1

sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha
sahan
Thilakshana
Dankelewathhtha


In [17]:
def funct2 (a,b):
    answer=b/a
    print(answer)
    

In [19]:
funct2(30,90)

3.0


In [25]:
import numpy as np
a = np.array([3,5,47,78,5,4,34,67,62,11,56,88,66])


In [27]:
a[0]

3

In [29]:
a[5]

4

In [33]:
print(a[2:6])

[47 78  5  4]


In [35]:
print(a[:6])

[ 3  5 47 78  5  4]


In [37]:
print(a[3:])

[78  5  4 34 67 62 11 56 88 66]


In [41]:
# This is how we create 4x4 array 
array=np.array([[1,3,7,4],[7,4,8,1],[9,5,7,3],[4,8,9,0]])

In [43]:
print(array)


[[1 3 7 4]
 [7 4 8 1]
 [9 5 7 3]
 [4 8 9 0]]


In [47]:
print(array[2,2])

7


In [51]:
print(array[1:3,1:2])
# Here[1:3,1:2]t mean, go 1 to 2 without 3 in row and go to 1 without 2 

[[4]
 [5]]


In [65]:
print(array[1,1:])

[4 8 1]


In [71]:
print(array[:,2:3])

[[7]
 [8]
 [7]
 [9]]


In [75]:
sahan = np.array([3,6,8,9,8,7,5,7,8,9,7,6,5,4,3,2,3,5,7,8])

In [77]:
sahan.sum()

120

In [79]:
sahan.mean()

6.0

In [81]:
sahan.min()

2

In [85]:
# Metrix multification
p=np.array([[2,4,3],[3,4,6],[8,6,9]])
q=np.array([[4,7,9],[5,6,9],[4,8,6]])

In [89]:
r=p+q
print(r)

[[ 6 11 12]
 [ 8 10 15]
 [12 14 15]]


In [91]:
q

array([[4, 7, 9],
       [5, 6, 9],
       [4, 8, 6]])

In [93]:
p+q

array([[ 6, 11, 12],
       [ 8, 10, 15],
       [12, 14, 15]])

In [95]:
p*10

array([[20, 40, 30],
       [30, 40, 60],
       [80, 60, 90]])

In [97]:
# Here this is not a real multification of 2d array. 
# we say this multification as "Hadamart product"
p*q

array([[ 8, 28, 27],
       [15, 24, 54],
       [32, 48, 54]])

In [101]:
# Here the way doing metrix multification
p.dot(q)

array([[ 40,  62,  72],
       [ 56,  93,  99],
       [ 98, 164, 180]])